version: '3.9'

services:
  redis:
    image: redis:6.2.3-alpine
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      NODE_ENV: development
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '10M'

  database:
    image: mysql
    container_name: database
    ports:
      - "9080:9080"
    environment:
       MYSQL_ROOT_PASSWORD: "root"
       MYSQL_TCP_PORT: "9080"
       MYSQL_DATABASE: "backend"
networks:
  default:
    name: backend_network



